### ISSUE TITLE
Visualize peers getting old data

### ISSUE THREAD

**Issue by goggledefogger** [common-tater/fireflower-visualizer#5]
When a peer gets in a state where they're getting old (delayed) data, let's show that in the viz.

**Comment by jessetane** [comment]
holding off on this one for now - as I understand it, getting old data would indicate that immediate action should be taken, so there would never be any perceivable length of time a node could remain in such a state

**Comment by jessetane** [comment]
as per our discussion, this was addressed by changing the reconnect color after a disconnect occurred due to old data
